<?php

namespace app\models;

use Yii;
use yii\base\Model;

/**
 * ContactForm is the model behind the contact form.
 */
class TestForm extends Model
{
    public $name;
    public $email;
    public $body;

	public function attributeLabels()
	{
		return [
			'name' => 'Имя',
			'email' => 'E-mail',
			'body' => 'Текст'
		];// TODO: Change the autogenerated stub
	}

	public function rules()
	{
		return [
			'required' => ['name','required', 'message' => 'Поле обязательно для заполнения'],
			'email' => ['email', 'email'],
			'min' => ['name', 'string', 'length' => [3,5], 'tooShort' => 'Меньше двух символов!', 'tooLong'=>'Надо меньше пяти!'],
			'my' => ['name', 'myRule', 'params'=> 'params'],
			'trim' => ['body', 'trim'],
		];
	}


	public function myRule($attr, $params)
	{
		if (!in_array($this->$attr,['Jek', 'Bobby'])) {
			$this->addError($attr, 'Jek or Bobby waiting');
		}
	}
}
